version: '3.8'

services:
  imageservice:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      REDIS_PORT: 6380
      REDIS_HOST: localhost
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
      SERVER_PORT: 8082
      SERVER_HOST: localhost
      CLIENT_HOST: localhost
      CLIENT_PORT: 3000
    networks:
      - app-network


  mongo:
    env_file:
      - .env
    image: mongo:latest
    hostname: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network


  redis:
    env_file:
      - .env
    image: redis:latest
    hostname: imageredis
    ports:
      - "6380:6380"
    volumes:
      - redis-data:/data
    networks:
      - app-network


volumes:
  mongo-data:
  redis-data:
networks:
  app-network:
    external: true
