spring:
  application:
    name: ImageService
  data:
    mongodb:
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
      database: ${MONGO_DB}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  servlet:

    multipart:
      max-request-size: 50MB
      max-file-size: 40MB
  cache:
    type: redis
  kafka:
    producer:
      properties:
        enable:
          idempotence: true
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    listener:
      auto-startup: false
    streams:
      auto-startup: false
    topic:
      imageSaved: image.saved
logging:
  file:
    name: logs/app/log
    path: logs
server:
  port: ${SERVER_PORT}
  host: ${SERVER_HOST}
client:
  hostName:
    ${CLIENT_HOST}
  port:
    ${CLIENT_PORT}

